notifee/react-native-notifee

- android/build.gradle
- Load Android Gradle Plugin conditionally
This wraps the Android Gradle plugin dependency in the buildscripts section of android/build.gradle in a conditional:
```
if (project == rootProject) {
// ... (dependency here)
}
```
The Android Gradle plugin is only required when opening the project stand-alone, not when it is included as a dependency. By doing this, the project opens correctly in Android Studio, and it can also be consumed as a native module dependency from an application project without affecting the app project (avoiding unnecessary downloads/conflicts/etc).
for more info, you can refer to [this thread](https://github.com/facebook/react-native/pull/25569) and especially [this comment.](https://github.com/facebook/react-native/pull/25569#issuecomment-532504277)
- ~~get project …
> fix(android,build): load Android Gradle Plugin conditionally

- src/NotifeeApiModule.ts
- src/types/Module.ts
fixes #60.
As per [RNFB](https://github.com/invertase/react-native-firebase/blob/1d7cd28f85d09d35805b59896809ca93aa436285/packages/messaging/lib/index.js#L212), return `1` for `requestPermission` method to let user know they've consented to receive notifications via the app.
> fix(android): return 1 for requestPermission

- src/types/NotificationIOS.ts
- src/validators/validateIOSNotification.ts
- validates `foregroundPresentationOptions` & passes in defaults if they aren't assigned by the user.
- added types for `foregroundPresentationOptions`
> feat(ios): ForegroundPresentationOptions

- tsconfig.json
It may be reasonably argued that this should be false and libs
should be checked, but I encounter a large batch of non-notifiee-related
errors when I attempt to run tsc with skipLibCheck: true
Because I understand there are good arguments to leave it on I will not be
offended at all if you disagree and close this
> Add skipLibCheck: true to tsconfig

- src/NotifeeApiModule.ts
Task key was wrong, it should be "app.notifee.foreground.task" instead of "app.notifee.notification.event"
This will remove warning "registerHeadlessTask called multiple times for same key" when using notifee.onBackgroundEvent and fix usage of foreground service task.
> fixed foreground service task registration

- android/build.gradle
fixes #88
When building for RN `0.60.0`, I noticed that the tasks for `@notifee_react-native` were preceding the tasks for `app` project (as noted in the screenshot) which is probably why `android` property is `null`.  The android gradle plugin hasn't been applied yet (I think). 
This PR ensures the `@notifee_react-native` project is dependent on the `app` project.
I've tested on RN version `0.60` & latest. Building successfully and notifications working.
> fix(react-native):  app project is evaluated first

- ios/RNNotifee/NotifeeApiModule.m
Fixes #110  ,
Background: UI API called on a background thread for [UIApplication applicationState].
Fix Applied: Wrap code that needs to be done on the main thread into the main-thread
> fix(ios): app freeze when getting push notification

- ios/RNNotifee/NotifeeApiModule.m
Put in a delay of 1 second around sending foreground + background events for iOS.
Maybe can exclude for certain foreground events for example, TRIGGER_NOTIFICATION_CREATED.
> delay sending events on ios

- android/src/main/java/io/invertase/notifee/NotifeeInitProvider.java
The gradle plugin team made some breaking changes between version 4.0 and 4.1, namely they removed propagation of Build.VERSION_NAME for libraries and encourage dynamic resolution of the same
https://issuetracker.google.com/issues/158695880#comment7
This breaks the build for anyone using Notifee and Android Gradle Plugin 4.0.1 (currently at rc02, so will likely release soon)
Noticed by @AndrewMorsillo (thanks!)
Fixes #143
patch-package format patch for affected customers to use prior to versioned release here, available on related issue: https://github.com/notifee/react-native-notifee/issues/143#issuecomment-687823683
> fix(android, build): Build.VERSION_NAME removed in gradle plugin 4.1

- RNNotifee.podspec
This is apparently the correct way to do it, as React-Core has the APIs native iOS modules actually need,
and they were only pulled in transitively by React, but in Xcode 12 something about the build system is racy
and leads to compile failures sometimes if this isn't direct.
CF https://github.com/facebook/react-native/issues/29633
> fix(ios, podspec): depend directly on React-Core, not React

- android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
- src/NotifeeApiModule.ts
- src/types/Module.ts
Fixes #126. 
API to help prevent the device from killing your app while it's in the background:
`isBatteryOptimizationEnabled()`
`openBatteryOptimizationSettings()`
Example:
```
// 1. checks if battery optimization is enabled
const batteryOptimizationEnabled = await notifee.isBatteryOptimizationEnabled();
if (batteryOptimizationEnabled) {
// 2. ask your users to disable the feature
Alert.alert(
'Restrictions Detected',
'To ensure notifications are delivered, please disable battery optimization for the app.',
[
// 3. launch intent to navigate the user to the appropriate screen
{
text: 'OK, open settings',
onPress: async () => await notifee.openBatteryOptimizationSettings(),
},
{
text: "Cancel",
onPress: () => console.log("Cancel Pressed"),
style: "cancel"
},
],
{ cancelable: false }
);
}; …
```
> feat(android): background restrictions helper api

- src/types/Trigger.ts
- src/validators/validateTrigger.ts
Fixes #140 To allow timestamp trigger to occur HOURLY, DAILY, or WEEKLY. 
Example:
```
Date date = Date.now();
date.setHours(11);
date.setMinutes(10);
const trigger: TimestampTrigger = {
type: TriggerType.TIMESTAMP,
timestamp: date.getTime(),
repeatFrequency: RepeatFrequency.WEEKLY
};
await notifee.createTriggerNotification(
{
id: '123',
title: 'Meeting with Jane',
body: 'Today at 11:20am',
android: {
channelId: 'your-channel-id',
},
},
trigger,
);
```
> feat(*): timestamp trigger update to accept a repeatFrequency property

- src/NotifeeApiModule.ts
Updated how background message handler is registered to prevent  React Native logging a warning when `onBackgroundEvent` isn't set.
Instead of React Native logging a warning:
`W/ReactNativeJS: No task registered for key app.notifee.notification-event`
A more descriptive warning will be logged by Notifee, and a fallback background message handler will be used instead:
`[notifee] no background message handler has been set. Set a handler via the "onBackgroundEvent" method.`
Addresses #111.
> fix(android): fix to prevent warning 'No task registered'

- RNNotifee.podspec
We definitely require cocoapods v1.10+ now that we use .xcframework to distribute
the library, but previously had not enforced it anywhere.
Fixes #230
This was taken from https://github.com/invertase/firestore-ios-sdk-frameworks/pull/22/files which has been released to public for a month now so it should work fine
> fix(ios): declaratively enforce v1.10+ of cocoapods

- android/notifee-json.gradle
Hello,
We in @Breadfast have an issue that makes us unable to build android so I have written a fix for it.
You can find the issue repeated in these issues:  #122 & #269 
Hope you find this fix helpful.
Thanks
> fix(android, build): do not create duplicate target variant tasks

- android/build.gradle
Related to #285 - when extracting the version I accidentally dropped the impl dependency
Where is the brown paper bag over head emoji?
This is the key line: https://github.com/notifee/react-native-notifee/compare/master...@mikehardy/fix-jwt-dependency?quick_pull=1#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR81
This is the upstream install documentation for reference https://github.com/jwtk/jjwt#dependencies
> fix(android, jwt): repair jwt gradle build dependency

- .eslintrc.js
- example/src/utils/notifications.ts
- jest-mock.js
- package.json
- src/NotifeeNativeModule.ts
- src/validators/validateNotification.ts
Updates all the dependencies and de-lints files.
Required for `yarn precommit` to pass on internal repo, paired with PR there
This was done in passing in order to prove that an Xcode 12.4 rebuild of the internal library passed all tests prior to submitting it
> build(deps): dependency updates

- example/src/utils/triggers.ts
- src/types/Trigger.ts
- src/validators/validateTrigger.ts
Alpha release published 1.9.0-alpha.0
New Timestamp Trigger API:
```
{
...
alarmManager: true | {
allowWhileIdle: true
}
}
```
E.G. (example [here](https://github.com/notifee/react-native-notifee/blob/bb70c8f52561623d264c282b523c9d58d766b498/example/src/utils/triggers.ts#L31)):
```
{
timestamp: date,
type: TriggerType.TIMESTAMP,
alarmManager: {
allowWhileIdle: true
}
}
```
> feat(android): support alarm manager for trigger notifications

- src/types/NotificationAndroid.ts
Related to #341 - this exposes the raw sound URI, and was used in testing on the related fix
For consideration: it may be useful to scan the NotificationChannelCompat API and incorporate all the new APIs for exposure but I fear scope creep / delay vs the necessary fix for #341
An easy+quick compromise might be to at least expose them all but mark them as read-only pending future support for setting them?
set of things not exposed includes information about conversations, whether user has customized a few items, and audio attributes (which may have been user-altered on the channel post-creation)
> feat(android, sound): expose raw soundURI on android

- src/types/Notification.ts
...since it now works on Android too.
I _was_ going to remove it from DisplayedNotification too (https://github.com/notifee/react-native-notifee/blob/master/src/types/Notification.ts#L126) but, from briefly testing it, it seems like you don't get the `trigger` property on Android when calling `getDisplayedNotifications()`. Is this a platform limitation on the Android side or an omission in Notifee and it _should_ be present on both?
> Remove @platform tags from docs which state `Trigger` is iOS specific

- android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
Been working through this in a few modules as I test the react-native 0.65 upgrade in a work project in order to fuzz-bust all the libraries
Here's the same in react-native-firebase https://github.com/invertase/react-native-firebase/pull/5616/files#diff-c887076b0c80d540aed1bfbb472cc8f20516634e8e72d53014c65d690bba4fb1
Also did it in netinfo and device-info modules - all seems to be working fine after being released a couple days.
I have this patch already test-integrated in my project via patch-package
> fix(android): add react-native 0.65 compatibility event emitter stubs
